### PR TITLE
[CB-11] Gets restaurant data associated with a zip code

### PR DESCRIPTION
**Pull request by olaade97**
* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)

New feature

* **What is the current behavior?What does the code do before you made the new changes?** 

Grabs data related to places associated with a specific zip code

* **What is the new behavior?**
Returns yelp search results associate with a specific zip code

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)

No

* **Other information**:

### CODE REVIEW

**Review by jadendick — COMMENTED** [review]
Looks good and the endpoint seems to work correctly. Just have to resolve the merge conflict, I think it is trying to overwrite part of the endpoint I wrote instead of just adding yours.

**Review by Codubee — CHANGES_REQUESTED** [review]
Any reason as to why the name of the file was changed from index.js to restaurants.js?

**Comment by olaade97** [comment]
I changed the name since I thought it was the source of a merge conflict but I can change it back when I get home.

**Review by Codubee — APPROVED** [review]

**Review by Codubee — APPROVED** [review]
LGTM!

**Review by jadendick — APPROVED** [review]
Looks good and works for me

**Pull request merged**
