### PR TITLE
CB-7-Routing

### PR DESCRIPTION
**Pull request by evanjelica**
* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Adds a routing component to the site

* **What is the current behavior? What does the code do before you made the new changes?** 
There is no routing between the components. So app defaults to displaying all of the components on the landing page.

* **What is the new behavior?**
The new change will add routing to the app. Users will be able to go to specific components by clicking on the tabs. 
Clicking on the home tab in the nav bar will lead to the default landing page.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
No, it shouldn't.

* **Other information**:
None

### CODE REVIEW

**Comment by Codubee** [comment]
Hi Anjelica, it looks like there are over 2k file changes. I think you might have pushed the node_modules by mistake. Would you mind removing them from you pr.

**Comment by evanjelica** [comment]
Hey Miguel, I tried removing the node_modules and added them to the .gitignore file but they're still showing up in the PR. 
How would I remove them from the PR?

**Review by jadendick — COMMENTED** [review]
Besides the node_modules files the router seems to work well. We might want the links in the NavBar component however.

**Comment by evanjelica** [comment]
Finally got it to remove the node_modules!
git add . wasn't working so I had to use git add -A instead

**Review by jadendick — COMMENTED** [review]
I might be mistaken but I think you should use a different Link component. The ReactBootStrap.Nav.Link seems to reload the page each time you click but if you use the Link from react-router-dom like you did initially then the page loads much faster. I would suggest switching this in the NavBar.

**Review by jadendick — APPROVED** [review]
Router seems to be working perfectly

**Review by Codubee — CHANGES_REQUESTED** [review]
Remove the changes from the pull request template and then ill approve.

**Comment by evanjelica** [comment]
The pull request template should be blank now.

**Review by Codubee — APPROVED** [review]

**Pull request merged**
